-- +goose Up
-- +goose StatementBegin
create table Articles
(
    id           bigint primary key generated by default as identity,
    source_id    bigint references Sources (id) on delete cascade not null,
    title        varchar(255)                   not null,
    link         varchar(255)                   not null unique,
    summary      text                           not null,
    published_at timestamp                      not null,
    created_at   timestamp                      not null default now(),
    posted_at    timestamp
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table if exists Articles;
-- +goose StatementEnd
