-- +goose Up
-- +goose StatementBegin
create table Topics
(
    id          bigint primary key generated by default as identity,
    name        varchar(255) not null,
    description varchar(255),
    created_at  timestamp    not null default now()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table if exists Topics;
-- +goose StatementEnd
