-- +goose Up
-- +goose StatementBegin
create table Sources
(
    id         bigint primary key generated by default as identity,
    name       varchar(255) not null,
    feed_url   varchar(255) not null unique,
    created_at timestamp    not null default now()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table if exists Sources;
-- +goose StatementEnd
